# Generated by Django 4.2.8 on 2025-12-11 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
