# Generated by Django 4.2.8 on 2024-02-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
